version: 0.2

phases:
  pre_build:
    commands:
      - echo Starting build...
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_REPO_NAME:latest 
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.us-west-1.amazonaws.com/$IMAGE_REPO_NAME:latest     
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image to us-east-1...
      - $(aws ecr get-login --no-include-email --region us-east-1)
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo Pushing the Docker image to us-west-2...
      - $(aws ecr get-login --no-include-email --region us-east-1)
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.us-west-2.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG